//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 25 21:29:14 BRST 2010
//----------------------------------------------------

package laxer;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int PONTOVIRGULA = 33;
	public static final int CONST = 26;
	public static final int OPAR = 29;
	public static final int ELSIF = 42;
	public static final int CPAR = 30;
	public static final int INTEGER = 8;
	public static final int REPEAT = 14;
	public static final int ARRAY = 22;
	public static final int PONTO = 35;
	public static final int VIRGULA = 34;
	public static final int WRITE = 24;
	public static final int NOT = 20;
	public static final int AND = 18;
	public static final int IGUAL = 36;
	public static final int MULTOP = 40;
	public static final int OR = 19;
	public static final int BEGIN = 5;
	public static final int ADDLOP = 41;
	public static final int UNTIL = 15;
	public static final int ATRI = 37;
	public static final int IF = 2;
	public static final int WRITELN = 13;
	public static final int RELOP = 39;
	public static final int ID = 27;
	public static final int OOPAR = 31;
	public static final int OF = 23;
	public static final int EOF = 0;
	public static final int BOOLEAN = 9;
	public static final int TRUE = 43;
	public static final int SIZE = 25;
	public static final int error = 1;
	public static final int OCPAR = 32;
	public static final int NUMBER = 28;
	public static final int PONTOPONTO = 38;
	public static final int REAL = 21;
	public static final int MODULE = 7;
	public static final int ELSE = 17;
	public static final int READ = 12;
	public static final int WHILE = 10;
	public static final int THEN = 16;
	public static final int END = 6;
	public static final int FALSE = 44;
	public static final int VAR = 3;
	public static final int PROCEDURE = 4;
	public static final int DO = 11;
}
