/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

public class ComExp extends Com {

	private Exp exp;

	public ComExp(Exp exp) {
		this.exp = exp;
	}

	public Exp getExp() {
		return exp;
	}

	public void setExp(Exp exp) {
		this.exp = exp;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("ComExp(\n");
		if (exp != null)
			buffer.append(exp.toString("  " + tab));
		else
			buffer.append(tab + "  null");
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [ComExp]");
		return buffer.toString();
	}

	@Override
	public void type_check() {
		exp.type_check();
	}

	@Override
	public void gen() {
		exp.gen();
		new Quad("IO", exp.addr, "", "");
	}

}
