/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

import type.Type;

public class DeclaVartype extends Decla {

	private String vartype;

	public DeclaVartype(String vartype) {
		this.vartype = vartype;
	}

	public DeclaVartype(String vartype, Type type) {
		this.vartype = vartype;
		this.type = type;
	}

	public String getVartype() {
		return vartype;
	}

	public void setVartype(String vartype) {
		this.vartype = vartype;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("DeclaVartype(\n");
		buffer.append("  " + tab + vartype);
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [DeclaVartype]");
		return buffer.toString();
	}

	@Override
	public void type_check() {
		if (vartype.equals("INTEGER"))
			type = INT;
		else
			type = BOOL;
	}

	@Override
	public void gen() {
		this.width = 4;
	}

}
