/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

import principal.goo;
import type.Type;
import SymbolTable.ConstInfo;
import SymbolTable.Info;
import SymbolTable.SymbolTable;

public class ExpIdSize extends Exp {

	private int id;
	private String size;

	public ExpIdSize(int id, String size) {
		this.id = id;
		this.size = size;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSize() {
		return size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("ExpIdSize(\n");
		buffer.append("  " + tab + id);
		buffer.append("\n");
		buffer.append("  " + tab + size);
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [ExpIdSize]");
		return buffer.toString();
	}

	@Override
	public StringBuffer to_postfix() {
		StringBuffer volta = new StringBuffer();
		volta.append(id);
		volta.append(".SIZE");
		return volta;
	}

	@Override
	public Type type_check() {
		SymbolTable ts = new SymbolTable();
		Info info = ts.get_info(id);
		_type = info.getType();
		if (!info.getTypeOld().equals("ARRAY")) {
			System.out.println("ERROR: " + ts.get_info(id).getName()
					+ " is not array");
			goo.podeContinuar = false;
		}
		return _type;
	}

	@Override
	public boolean check_const() {
		SymbolTable ts = new SymbolTable();
		Info i = ts.get_info(id);
		if (i.category() == 2) {
			ConstInfo ci = (ConstInfo) i;
			cvalue = ci.getConst_value();
			return true;
		} else {
			return false;
		}
	}

	public StringBuffer codigoInter() {
		StringBuffer v = new StringBuffer();
		SymbolTable ts = new SymbolTable();
		Info i = ts.get_info(id);
		v.append(i.getName());
		v.append(".SIZE");
		return v;
	}

	public boolean equals(Object obj) {
		return this.toString().equals(obj.toString());
	}

	@Override
	public void gen() {
		SymbolTable ts = new SymbolTable();
		Info i = ts.get_info(id);
		this.addr = i.getName();
	}

}
