/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

import type.Type;

public class ExpValor extends Exp {

	private int valor;

	public ExpValor(int valor) {
		this.valor = valor;
	}

	public int getValor() {
		return valor;
	}

	public void setValor(int valor) {
		this.valor = valor;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("ExpValor(\n");
		buffer.append("  " + tab + valor);
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [ExpValor]");
		return buffer.toString();
	}

	@Override
	public boolean check_const() {
		cvalue = valor;
		return true;
	}

	@Override
	public StringBuffer to_postfix() {
		StringBuffer ret = new StringBuffer();
		ret.append(valor);
		return ret;
	}

	@Override
	public Type type_check() {
		return _type = INT;
	}

	public boolean equals(Object obj) {
		return this.toString().equals(obj.toString());
	}

	@Override
	public void gen() {
		this.width = 4;
		this.addr = "$" + Integer.toString(valor);
		ControleDead e = new ControleDead();
		e.setVar(this.addr);
		e.setInfo("-1");
		Quad.dead.add(e);
		Variaveis v = new Variaveis();
		v.setV(this.addr);
		Quad.DV.add(v);
	}

}
