/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

import SymbolTable.Info;
import SymbolTable.SymbolTable;

public class Module {

	private int id1;
	private Decla decla;
	private Decla decla2;
	private int id2;

	public Module(int id1, Decla decla, Decla decla2, int id2) {
		this.id1 = id1;
		this.decla = decla;
		this.decla2 = decla2;
		this.id2 = id2;
	}

	public int getId1() {
		return id1;
	}

	public void setId1(int id1) {
		this.id1 = id1;
	}

	public Decla getDecla() {
		return decla;
	}

	public void setDecla(Decla decla) {
		this.decla = decla;
	}

	public Decla getDecla2() {
		return decla2;
	}

	public void setDecla2(Decla decla2) {
		this.decla2 = decla2;
	}

	public int getId2() {
		return id2;
	}

	public void setId2(int id2) {
		this.id2 = id2;
	}

	public String toString() {
		return toString("");
	}

	public void type_check() {
		SymbolTable ts = new SymbolTable();
		Info vi = ts.get_info(id1);
		vi.setType(Decla.VOID);
		ts.edit_info(id1, vi);
		decla.type_check();
		decla2.type_check();
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("Module(\n");
		buffer.append("  " + tab + id1);
		buffer.append("\n");
		if (decla != null)
			buffer.append(decla.toString("  " + tab));
		else
			buffer.append(tab + "  null");
		buffer.append("\n");
		if (decla2 != null)
			buffer.append(decla2.toString("  " + tab));
		else
			buffer.append(tab + "  null");
		buffer.append("\n");
		buffer.append("  " + tab + id2);
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [Module]");
		return buffer.toString();
	}

	public StringBuffer codigoInter() {

		decla.gen();
		new Quad("main", "", "", "");
		decla2.gen();
		new Quad("exit", "", "", "");
		return null;
	}

}
