/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

import principal.goo;
import type.Type;

public class ComRepeat extends Com {

	private Com com;
	private Exp exp;

	public ComRepeat(Com com, Exp exp) {
		this.com = com;
		this.exp = exp;
	}

	public Com getCom() {
		return com;
	}

	public void setCom(Com com) {
		this.com = com;
	}

	public Exp getExp() {
		return exp;
	}

	public void setExp(Exp exp) {
		this.exp = exp;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("ComRepeat(\n");
		if (com != null)
			buffer.append(com.toString("  " + tab));
		else
			buffer.append(tab + "  null");
		buffer.append("\n");
		if (exp != null)
			buffer.append(exp.toString("  " + tab));
		else
			buffer.append(tab + "  null");
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [ComRepeat]");
		return buffer.toString();
	}

	@Override
	public void type_check() {
		Type t = exp.type_check();
		if (t != ERROR && t != BOOL) {
			goo.podeContinuar = false;
			System.out.println("invalid type in condition");
		}
		com.type_check();
	}

	@Override
	public void gen() {
		com.gen();
		exp.gen();
	}

}
