/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

import SymbolTable.Info;
import SymbolTable.SymbolTable;
import SymbolTable.VarInfo;

public class DeclaIdList extends Decla {

	private int id;
	private Decla decla;

	public DeclaIdList(int id, Decla decla) {
		this.id = id;
		this.decla = decla;
	}

	public int getid() {
		return id;
	}

	public void setid(int id) {
		this.id = id;
	}

	public Decla getDecla() {
		return decla;
	}

	public void setDecla(Decla decla) {
		this.decla = decla;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("DeclaIdList(\n");
		buffer.append("  " + tab + id);
		buffer.append("\n");
		if (decla != null)
			buffer.append(decla.toString("  " + tab));
		else
			buffer.append(tab + "  null");
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [DeclaIdList]");
		return buffer.toString();
	}

	@Override
	public void type_check() {
		// MUDEI
		decla.type_check();
		SymbolTable ts = new SymbolTable();
		// System.out.println(ts.get_info(id).getClass());
		VarInfo vi = (VarInfo) ts.get_info(id);
		if (vi.getTypeOld().equals("INTEGER")) {
			vi.setType(INT);
			ts.edit_info(id, vi);
		} else if (vi.getTypeOld().equals("BOOLEAN")) {
			vi.setType(BOOL);
			ts.edit_info(id, vi);
		} else if (vi.getTypeOld().equals("ARRAYINTEGER")) {
			vi.setType(INTARRAY);
			vi.setTypeOld("ARRAY");
			ts.edit_info(id, vi);
		} else if (vi.getTypeOld().equals("ARRAYBOOLEAN")) {
			vi.setType(BOOLARRAY);
			vi.setTypeOld("ARRAY");
			ts.edit_info(id, vi);
		} else {
			vi.setType(ERROR);
			ts.edit_info(id, vi);
		}

	}

	@Override
	public void gen() {
		SymbolTable ts = new SymbolTable();
		Info vi = ts.get_info(id);
		int temp = contDesloca++ * 4;
		vi.setOffsets(temp);
		new Quad(globalOuLocal, "id" + id, "" + temp, "");
		this.width = 4;
		ControleDead e = new ControleDead();
		e.setVar("id" + id);
		e.setInfo("-1");
		Quad.dead.add(e);
		Variaveis v = new Variaveis();
		v.setV("id" + id);
		Quad.DV.add(v);
		decla.gen();
		this.width = decla.width + this.width;
	}

}
