/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

public class DeclaCom extends Decla {

	private Com com;

	public DeclaCom(Com com) {
		this.com = com;
	}

	public Com getCom() {
		return com;
	}

	public void setCom(Com com) {
		this.com = com;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("DeclaCom(\n");
		if (com != null)
			buffer.append(com.toString("  " + tab));
		else
			buffer.append(tab + "  null");
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [DeclaCom]");
		return buffer.toString();
	}

	@Override
	public void type_check() {
		if (com != null)
			com.type_check();
	}

	@Override
	public void gen() {
		if (com != null)
			com.gen();
	}

}
