/*
 * Generated by classgen, version 1.3
 * 24/09/10 22:45
 */
package controle;

import type.Type;

public class ExpBoolean extends Exp {

	private boolean booo;

	public ExpBoolean(boolean booo) {
		this.booo = booo;
	}

	public boolean getBooo() {
		return booo;
	}

	public void setBooo(boolean booo) {
		this.booo = booo;
	}

	public String toString(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("ExpBoolean(\n");
		buffer.append("  " + tab + booo);
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [ExpBoolean]");
		return buffer.toString();
	}

	@Override
	public StringBuffer to_postfix() {
		StringBuffer ret = new StringBuffer();
		if (booo)
			ret.append("TRUE");
		else
			ret.append("FALSE");
		return ret;
	}

	@Override
	public void gen() {
		this.width = 4;
		if (booo)
			this.addr = "TRUE";
		else
			this.addr = "FALSE";
	}

	@Override
	public Type type_check() {
		return _type = BOOL;
	}

	public boolean equals(Object obj) {
		return this.toString().equals(obj.toString());
	}
}
